@baseUrl = http://localhost:3333/core
@authToken = {{loginauthenticate.response.body.access_token}}
@psychologist_id = {{loginauthenticate.response.body.user.id}}

# @name loginauthenticate
POST http://localhost:3333/core/psychologist/login HTTP/1.1
Content-Type: application/json

{
  "email": "joe_doe@email.com",
  "password": "joe-password"
}

####

# @name create_clinic

POST http://localhost:3333/core/clinic/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "New Clinic",
  "psychologistId": "{{psychologist_id}}",
  "city": "Fake City",
  "state": "Fake State"
}

####

# @name update_clinic

PATCH http://localhost:3333/core/clinic/8d40bb8d-fd0b-4753-83cf-87bac7b3c6e7/update HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "New Name Clinic"
}


####

# @name delete_clinic

DELETE http://localhost:3333/core/clinic/159b4134-9d2a-4198-98c3-ac031eb31998/delete HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}
