version: '3.8'

volumes:
  # postgresql data
  core-rest-api-postgres-data:
    driver: local

services:
  postgres:
    container_name: core-rest-api-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: cliniccontrol
      POSTGRES_PASSWORD: cliniccontrolpassword
      POSTGRES_DB: core-rest-api
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA: public

      # PGDATA: /data/postgres
    volumes:
      # - ./data/pg:/data/postgres
      - core-rest-api-postgres-data:/var/lib/postgresql/data
