@baseUrl = http://localhost:3333/core
@authToken = {{loginauthenticate.response.body.access_token}}

### Create New User

# @name create_psychologist
POST http://localhost:3333/core/psychologist/create HTTP/1.1
Content-Type: application/json
api-key: api-key

{
  "name": "Novo Usuario",
  "email": "novo_usuario_33@gmail.com",
  "password": "01212012",
  "role": "PSYCHOLOGIST",
  "plan": "PREMIUM"
}

### Authenticate User

# @name loginauthenticate
POST http://localhost:3333/core/psychologist/login HTTP/1.1
Content-Type: application/json

{
  "email": "novo_usuario_33@gmail.com",
  "password": "01212012"
}

###

# @name me
GET http://localhost:3333/core/psychologist/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}
