@authToken = {{$dotenv AUTH_TOKEN}}
@apiKey = {{$dotenv API_KEY}}

### Create New Appointment Registry

# @name create_patient_appointment_registry
POST http://localhost:3333/core/appointment-registry/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "registry": {
    "observations": "well"
  },
  "psychologistId": "{{$dotenv PSYCHOLOGIST_ID}}",
  "patientId": "{{$dotenv PATIENT_ID}}"
}

### delete Registry

# @name delete_patient_appointment_registry
DELETE http://localhost:3333/core/appointment-registry/{{$dotenv PATIENT_APPOINTMENT_REGISTRY_ID}}/delete HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}
