@authToken = {{$dotenv AUTH_TOKEN}}
@apiKey = {{$dotenv API_KEY}}

### Create New User

# @name create_psychologist
POST http://localhost:3333/core/psychologist/create HTTP/1.1
Content-Type: application/json
api-key: api-key

{
  "name": "{{$dotenv PSYCHOLOGIST_NAME}}",
  "email": "{{$dotenv PSYCHOLOGIST_EMAIL}}",
  "password": "{{$dotenv PSYCHOLOGIST_PASSWORD}}",
  "role": "PSYCHOLOGIST",
  "plan": "PREMIUM"
}

### Authenticate User

# @name loginauthenticate
POST http://localhost:3333/core/psychologist/login HTTP/1.1
Content-Type: application/json

{
  "email": "{{$dotenv PSYCHOLOGIST_EMAIL}}",
  "password": "{{$dotenv PSYCHOLOGIST_PASSWORD}}"
}

### Update User

# @name update_psychologist
PATCH http://localhost:3333/core/psychologist/{{$dotenv PSYCHOLOGIST_ID}}/update HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "password": "joe-password-updated"
}

### Delete User

# @name delete_psychologist
DELETE http://localhost:3333/core/psychologist/{{$dotenv PSYCHOLOGIST_EMAIL}}/delete HTTP/1.1
# DELETE http://localhost:3333/core/psychologist/wrong_email@gmail.com/delete HTTP/1.1
# DELETE http://localhost:3333/core/psychologist/invalid_email/delete HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}
