#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Husky pre commit script..."

echo "Running Project Lint Validation..."
pnpm exec nx run-many --target=lint --all=true --parallel=3

echo "Running Unit Tests..."
pnpm run test:unit
