@baseUrl = http://localhost:3333/core
@authToken = {{loginauthenticate.response.body.access_token}}
@psychologist_id = {{loginauthenticate.response.body.user.id}}

### Authenticate User

# @name loginauthenticate
POST http://localhost:3333/core/psychologist/login HTTP/1.1
Content-Type: application/json

{
  "email": "joe_doe@email.com",
  "password": "joe-password"
}

### Create a new patient
POST http://localhost:3333/core/patient/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Abigail Doe",
  "email": "abigail.doe@email.com",
  "cpf": "123.456.789-00",
  "telephone": "(11) 99999-9999",
  "paymentMethod": "CREDIT_CARD",
  "psychologistId": "{{psychologist_id}}",
  "clinicId": "200d53ab-3715-4c5e-9eb6-8977659ea3e7"
}
