name: Run Unit Tests

on: [pull_request]

env:
  HUSKY: 0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18'

      - name: Install dependencies
        run: pnpm install

      - name: Run Unit Tests
        run: pnpm test:unit
